### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]' imported by the module 'CoreModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by minhtoanho** [ElderByte-/ngx-simple-webstorage#3]
Hi team,

I tried to use this module with ngx-jwt-auth but got this error log.

This's my config
```
LoggerModule.forRoot({ serverLoggingUrl: '/api/logs', level: NgxLoggerLevel.DEBUG, serverLogLevel: NgxLoggerLevel.ERROR }),
    SimpleWebStorageModule.forRoot(),
    JwtAuthModule.forRoot({
      localLoginRoute: '/signin',
      accessDeniedRoute: '/access_denied',
      obtainTokenUrl: environment.apiUrl + '/oauth/token',
    }),
```
Please help to review this.

Best thanks!

**Comment by minhtoanho** [comment]
Try to move these config to app module and it's working right now.

**Comment by IsNull** [comment]
I have encountered this error after upgrading to angular 5, but it was not specific to any library.

The -aot build and the prod build where working fine, but the development serve had your error.

There are two tweaks you can try: Use AOT in your dev build - its very fast with the latest compiler.
Another issue can be a tweaked tsconfig.json where you disabled the metadata generation.

**Comment by minhtoanho** [comment]
Thanks @IsNull! 

I try to use AOT and it worked.

Thanks a lot!

**Comment by Mc128k** [comment]
Hi, I'm having this problem, and I already checked that the `emitDecoratorMetadata` option is enabled for the `tsconfig.json` and `tsconfig.webpack.json` files. Any other ideas?

**Comment by Mc128k** [comment]
Oh, I think I got it. YOUR library doesn't have the `emitDecoratorMetadata` flag active. I believe you should add it. I solved by recompiling it and manually including it in `node_modules` (which is bad and temporary, but it works).
